name: Test print inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy
        required: true
        type: environment

jobs:
  print_inputs:
    name: Print Inputs
    runs-on: ubuntu-22.04
    environment: dev

    steps:
      - name: Summary
        id: summary
        run: |
          echo "- environment: \`${{ inputs.environment }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- ref: \`${{ github.ref }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- print secret? `${{ secrets.AWS_REGION }}`" >> $GITHUB_STEP_SUMMARY






